"""
vehicles/vehicle_types.py
=========================
Generates vehicle_types.add.xml with randomised driver profiles.

Each vehicle class gets VARIANTS_PER_TYPE distinct vType definitions,
each with individually randomised sigma, tau, minGap, speedFactor,
accel, decel, and lane-change parameters drawn from traffic.env ranges.

This is what makes the simulation look like real traffic: Car_1 might
tailgate at 110% speed limit while Car_2 keeps a large gap at 85%.
Trucks vary in how sluggishly they accelerate. Motorcycles are erratic.

Colour variation: cars get a slight blue hue shift per profile so you
can visually distinguish different driver types in the GUI.
"""

import os, sys, random

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config.simulation_config import (
    CAR_MAX_SPEED, CAR_ACCEL, CAR_DECEL,
    TRUCK_MAX_SPEED, TRUCK_ACCEL, TRUCK_DECEL,
    BUS_MAX_SPEED, BUS_ACCEL, BUS_DECEL,
    MOTO_MAX_SPEED, MOTO_ACCEL, MOTO_DECEL,
    AMBULANCE_SPEED_MS,
)
from config.env_loader import ENV

VEHICLES_DIR      = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH       = os.path.join(VEHICLES_DIR, "vehicle_types.add.xml")
VARIANTS_PER_TYPE = 8

PC  = "HBEFA3/PC_G_EU4"
HDV = "HBEFA3/HDV_D_EU4"


def _clamp(v, lo, hi):
    return max(lo, min(hi, v))


def _gauss_clamp(rng, mean, std, lo, hi):
    for _ in range(30):
        v = rng.gauss(mean, std)
        if lo <= v <= hi:
            return round(v, 3)
    return round(_clamp(rng.gauss(mean, std), lo, hi), 3)


def _vary(rng, base, frac):
    d = base * frac
    return round(rng.uniform(base - d, base + d), 2)


def _write_vtype(f, vid, accel, decel, sigma, tau, min_gap,
                 max_speed, speed_factor,
                 length, width, height, shape, color,
                 capacity, emission,
                 lcs, lcc, lcsg, lckr, lci, jmfps, jmsm):
    f.write('    <vType id="{id}"\n'.format(id=vid))
    f.write('           accel="{}" decel="{}" sigma="{}"\n'.format(accel, decel, sigma))
    f.write('           tau="{}" minGap="{}"\n'.format(tau, min_gap))
    f.write('           maxSpeed="{}" speedFactor="{}"\n'.format(max_speed, speed_factor))
    f.write('           length="{}" width="{}" height="{}"\n'.format(length, width, height))
    f.write('           guiShape="{}" color="{}"\n'.format(shape, color))
    f.write('           personCapacity="{}" emissionClass="{}"\n'.format(capacity, emission))
    f.write('           lcStrategic="{}" lcCooperative="{}"\n'.format(lcs, lcc))
    f.write('           lcSpeedGain="{}" lcKeepRight="{}"\n'.format(lcsg, lckr))
    f.write('           lcImpatience="{}"\n'.format(lci))
    f.write('           jmIgnoreFoeProb="{}" jmSigmaMinorWait="{}"/>\n'.format(jmfps, jmsm))


def _lc(rng):
    c = _clamp
    return (
        round(c(rng.gauss(ENV.LC_STRATEGIC,    0.15), 0.0, 1.0), 2),
        round(c(rng.gauss(ENV.LC_COOPERATIVE,  0.15), 0.0, 1.0), 2),
        round(c(rng.gauss(ENV.LC_SPEED_GAIN,   0.05), 0.0, 1.0), 2),
        round(c(rng.gauss(ENV.LC_KEEP_RIGHT,   0.15), 0.0, 1.0), 2),
        round(c(rng.gauss(ENV.LC_IMPATIENCE,   0.10), 0.0, 1.0), 2),
    )


def _jm(rng):
    c = _clamp
    return (
        round(c(rng.gauss(ENV.JUNCTION_MODEL_IGNORE_FPS,  0.01), 0.0, 0.3), 3),
        round(c(rng.gauss(ENV.JUNCTION_MODEL_SIGMA_MINOR, 0.10), 0.0, 1.0), 2),
    )


def write_vehicle_types(path=OUTPUT_PATH):
    seed = ENV.RANDOM_SEED if ENV.RANDOM_SEED >= 0 else None
    rng  = random.Random(seed)

    with open(path, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write('<!-- vehicle_types.add.xml  -  {} profiles per class\n'.format(VARIANTS_PER_TYPE))
        f.write('     Generated by vehicles/vehicle_types.py\n')
        f.write('     Randomised from ranges in traffic.env -->\n')
        f.write('<additional>\n\n')

        # ---- Cars -----------------------------------------------------------
        f.write('    <!-- CARS: {} driver profiles -->\n'.format(VARIANTS_PER_TYPE))
        for i in range(VARIANTS_PER_TYPE):
            sigma = round(rng.uniform(ENV.CAR_SIGMA_MIN,  ENV.CAR_SIGMA_MAX),  2)
            tau   = round(rng.uniform(ENV.TAU_MIN,        ENV.TAU_MAX),         2)
            mg    = round(rng.uniform(ENV.MIN_GAP_MIN,    ENV.MIN_GAP_MAX),     2)
            sf    = _gauss_clamp(rng, ENV.SPEED_FACTOR_MEAN, ENV.SPEED_FACTOR_STD,
                                 ENV.MIN_SPEED_FACTOR_CAR, ENV.MAX_SPEED_FACTOR_CAR)
            acc   = _vary(rng, CAR_ACCEL, ENV.ACCEL_VARIATION)
            dec   = _vary(rng, CAR_DECEL, ENV.DECEL_VARIATION)
            r     = round(_clamp(0.27 + rng.uniform(-0.05, 0.12), 0.15, 0.55), 2)
            g     = round(_clamp(0.51 + rng.uniform(-0.08, 0.08), 0.35, 0.70), 2)
            b     = round(_clamp(0.71 + rng.uniform(-0.05, 0.15), 0.55, 0.92), 2)
            _write_vtype(f, "car_{}".format(i), acc, dec, sigma, tau, mg,
                         CAR_MAX_SPEED, sf, 4.5, 1.8, 1.5, "passenger",
                         "{},{},{}".format(r, g, b), 4, PC, *_lc(rng), *_jm(rng))

        # ---- Trucks ---------------------------------------------------------
        f.write('\n    <!-- TRUCKS: {} driver profiles -->\n'.format(VARIANTS_PER_TYPE))
        for i in range(VARIANTS_PER_TYPE):
            sigma = round(rng.uniform(ENV.TRUCK_SIGMA_MIN, ENV.TRUCK_SIGMA_MAX), 2)
            tau   = round(rng.uniform(ENV.TAU_MIN + 0.2,  ENV.TAU_MAX + 0.4),   2)
            mg    = round(rng.uniform(ENV.MIN_GAP_MIN + 0.5, ENV.MIN_GAP_MAX + 1.5), 2)
            sf    = _gauss_clamp(rng, ENV.SPEED_FACTOR_MEAN - 0.10, ENV.SPEED_FACTOR_STD,
                                 ENV.MIN_SPEED_FACTOR_HGV, ENV.MAX_SPEED_FACTOR_HGV)
            acc   = _vary(rng, TRUCK_ACCEL, ENV.ACCEL_VARIATION)
            dec   = _vary(rng, TRUCK_DECEL, ENV.DECEL_VARIATION)
            s     = round(rng.uniform(0.22, 0.42), 2)
            _write_vtype(f, "truck_{}".format(i), acc, dec, sigma, tau, mg,
                         TRUCK_MAX_SPEED, sf, 12.0, 2.5, 3.5, "truck",
                         "{s},{s},{s}".format(s=s), 2, HDV, *_lc(rng), *_jm(rng))

        # ---- Buses ----------------------------------------------------------
        f.write('\n    <!-- BUSES: {} driver profiles -->\n'.format(VARIANTS_PER_TYPE))
        for i in range(VARIANTS_PER_TYPE):
            sigma = round(rng.uniform(ENV.BUS_SIGMA_MIN,   ENV.BUS_SIGMA_MAX),  2)
            tau   = round(rng.uniform(ENV.TAU_MIN + 0.1,   ENV.TAU_MAX),        2)
            mg    = round(rng.uniform(ENV.MIN_GAP_MIN + 0.3, ENV.MIN_GAP_MAX + 0.5), 2)
            sf    = _gauss_clamp(rng, ENV.SPEED_FACTOR_MEAN - 0.05,
                                 ENV.SPEED_FACTOR_STD * 0.6,
                                 ENV.MIN_SPEED_FACTOR_HGV, ENV.MAX_SPEED_FACTOR_CAR)
            acc   = _vary(rng, BUS_ACCEL, ENV.ACCEL_VARIATION)
            dec   = _vary(rng, BUS_DECEL, ENV.DECEL_VARIATION)
            gv    = round(_clamp(0.55 + rng.uniform(-0.10, 0.10), 0.40, 0.70), 2)
            _write_vtype(f, "bus_{}".format(i), acc, dec, sigma, tau, mg,
                         BUS_MAX_SPEED, sf, 12.0, 2.5, 3.2, "bus",
                         "0.13,{},0.13".format(gv), 60, HDV, *_lc(rng), *_jm(rng))

        # ---- Motorcycles ----------------------------------------------------
        f.write('\n    <!-- MOTORCYCLES: {} driver profiles -->\n'.format(VARIANTS_PER_TYPE))
        for i in range(VARIANTS_PER_TYPE):
            sigma = round(rng.uniform(ENV.MOTO_SIGMA_MIN,  ENV.MOTO_SIGMA_MAX),  2)
            tau   = round(rng.uniform(max(0.4, ENV.TAU_MIN - 0.1),
                                      max(0.8, ENV.TAU_MAX - 0.3)),               2)
            mg    = round(rng.uniform(max(0.8, ENV.MIN_GAP_MIN - 0.2),
                                      max(1.5, ENV.MIN_GAP_MAX - 1.0)),           2)
            sf    = _gauss_clamp(rng, ENV.SPEED_FACTOR_MEAN + 0.08,
                                 ENV.SPEED_FACTOR_STD * 1.3,
                                 ENV.MIN_SPEED_FACTOR_CAR,
                                 min(ENV.MAX_SPEED_FACTOR_CAR + 0.2, 1.5))
            acc   = _vary(rng, MOTO_ACCEL, ENV.ACCEL_VARIATION)
            dec   = _vary(rng, MOTO_DECEL, ENV.DECEL_VARIATION)
            og    = round(_clamp(0.45 + rng.uniform(-0.10, 0.15), 0.30, 0.65), 2)
            _write_vtype(f, "motorcycle_{}".format(i), acc, dec, sigma, tau, mg,
                         MOTO_MAX_SPEED, sf, 2.2, 0.8, 1.2, "motorcycle",
                         "1.0,{},0.0".format(og), 2, PC, *_lc(rng), *_jm(rng))

        # ---- Ambulance ------------------------------------------------------
        f.write('\n    <!-- AMBULANCE: single type -->\n')
        _write_vtype(f, "ambulance", 3.5, 6.0, 0.1, 0.6, 1.5,
                     AMBULANCE_SPEED_MS, 1.0, 6.0, 2.1, 2.3, "delivery",
                     "1.0,0.0,0.0", 2, PC,
                     1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0)

        # ---- VIP Car --------------------------------------------------------
        f.write('\n    <!-- VIP CAR: gold, single type -->\n')
        _write_vtype(f, "vip_car", CAR_ACCEL, CAR_DECEL, 0.1, 0.8, 2.0,
                     round(CAR_MAX_SPEED * 1.1, 2), 1.05,
                     4.8, 1.9, 1.5, "passenger", "1.0,0.84,0.0", 4, PC,
                     1.0, 0.5, 0.05, 0.5, 0.8, 0.0, 0.2)

        f.write('\n</additional>\n')

    print("  [vtypes]  {} ({} variants x 4 classes + ambulance + vip)".format(
        path, VARIANTS_PER_TYPE))
    return path


def get_type_ids():
    """Returns dict of class -> list of vType IDs for use by route_generator."""
    return {
        "car":        ["car_{}".format(i)        for i in range(VARIANTS_PER_TYPE)],
        "truck":      ["truck_{}".format(i)      for i in range(VARIANTS_PER_TYPE)],
        "bus":        ["bus_{}".format(i)        for i in range(VARIANTS_PER_TYPE)],
        "motorcycle": ["motorcycle_{}".format(i) for i in range(VARIANTS_PER_TYPE)],
        "ambulance":  ["ambulance"],
        "vip_car":    ["vip_car"],
    }


if __name__ == "__main__":
    write_vehicle_types()
